### ISSUE TITLE
[Enhancement] EKS Pod Identity

### ISSUE THREAD

**Issue by chipzoller** [kubecost/docs#1001]
### Description

As of Kubecost 2.2.0, [EKS Pod Identity](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-eks-pod-identity/) is now supported. This doesn't appear to be documented.

**Comment by srpomeroy** [comment]
There are some docs in OpenCost as a starting point.
https://github.com/opencost/opencost-website/pull/206/files

**Comment by bstuder99** [comment]
Got a meeting on Monday with Steven, will have something more substantial then

**Comment by srpomeroy** [comment]
I do not believe we need to annotate the service account with EKS Pod Identities.

I can also help here; we are currently testing in our demo environment.
