### ISSUE TITLE
[Bug] Change instances of "Cloud Cost Settings" to "Cloud Integrations"

### ISSUE THREAD

**Issue by chipzoller** [kubecost/docs#1008]
### Page link

https://docs.kubecost.com/install-and-configure/install/cloud-integration/aws-cloud-integrations

### Description

On all pages, not just this one, anywhere where "Cloud Cost Settings" are referenced in the Settings page need to be updated to "Cloud Integrations" as the latter is what is now used in the UI.

### Expected behavior

Users are correctly directed to the Cloud Integrations section in the Settings UI.

**Comment by bstuder99** [comment]
@nealormsbee Can you weigh in here? It looks like the process we describe in the AWS doc describe the old system of manually adding integration details, but it looks like that was scrapped some time ago. Can't remember the specific update, but is there any way to configure cloud integration details via the UI now?

**Comment by bstuder99** [comment]
Somewhat related, I also don't see the Currency section in Nightly, how are users configuring custom currency types in the UI now?

**Comment by chipzoller** [comment]
> @nealormsbee Can you weigh in here? It looks like the process we describe in the AWS doc describe the old system of manually adding integration details, but it looks like that was scrapped some time ago. Can't remember the specific update, but is there any way to configure cloud integration details via the UI now?

I'm not Neal but yes there is, via Cloud Integrations. I logged a bug because this currently appears broken but it's supposed to work today.

**Comment by nealormsbee** [comment]
It's a good question. We did previously have a way to edit an integration...but that was back when we only supported a single integration per cloud provider, and we stored the secrets differently. I'm not sure if we now have a technical limitation preventing us from editing integrations, or just haven't built an API for it, or _have_ and API for it and just haven't built a frontend for it.

@Sean-Holcomb I think you're the expert here. Can you weigh in?

**Comment by chipzoller** [comment]
Not trying to disrupt the convo, but it is meandering away from the point of this issue. The issue is only to change the references from the old name to the new. Regardless of how they're configured, the docs should still direct users to the right section of the UI by using the current descriptions.

**Comment by bstuder99** [comment]
Chip, the point is if the user can't update an existing cloud integration via UI, then this entire step you've linked to should just be removed (attach service key via UI). I can issue corrections on this today but it looks like some of the functionality has changed as well, not just the name
