### ISSUE TITLE
[Enhancement] Add note/warning about potential need to increase Lambda concurrent execution quota

### ISSUE THREAD

**Issue by chipzoller** [kubecost/docs#1018]
### Description

In step 5 of integrating Kubecost with AWS [here](https://docs.kubecost.com/install-and-configure/install/cloud-integration/aws-cloud-integrations#step-5-provide-cur-config-values-to-kubecost), there is a chance some users will run into failure when running the CFT in their account due to low Lambda concurrent execution values. The fix for this is to request a quota increase in the AWS console. By default, the value may be set at 10, which is too low to allow the template to execute. Further details can be found [here](https://benellis.cloud/my-lambda-concurrency-applied-quota-is-only-10-but-why).

![image](https://github.com/kubecost/docs/assets/29008123/d3931390-138a-4d8c-b623-1aa90fe950ec)

We need to add a note/warning in this relevant section of the docs explaining about this and directing users to perform a quota increase.

**Comment by bstuder99** [comment]
Will have a correction for these today

**Comment by bstuder99** [comment]
Is there a reason this troubleshooting is specific to Step 5? Seems unrelated to setting up their CFT

**Comment by chipzoller** [comment]
I think I misspoke and it's part of step 2.
