### ISSUE TITLE
[Enhancement] Making external AWS docs on Athena setup mandatory

### ISSUE THREAD

**Issue by chipzoller** [kubecost/docs#1020]
### Description

In step 2 of the AWS integration [here](https://docs.kubecost.com/install-and-configure/install/cloud-integration/aws-cloud-integrations#step-2-setting-up-athena), the first paragraph currently shows the following.

> As part of the CUR creation process, Amazon also creates a CloudFormation template that is used to create the Athena integration. It is created in the CUR S3 bucket, listed in the Objects tab in the path s3-path-prefix/cur-name and typically has the filename crawler-cfn.yml. This .yml is your necessary CloudFormation template. You will need it in order to complete the CUR Athena integration. For more information, see the AWS doc [Setting up Athena using AWS CloudFormation templates](https://docs.aws.amazon.com/cur/latest/userguide/use-athena-cf.html).

The last sentence there suggests that the link to the AWS page is optional or informative. It is not. This step MUST be followed in order to proceed to additional steps.

The docs need to clearly state users should follow the linked procedure before proceeding to the next step or else the integration will not be possible.

**Comment by bstuder99** [comment]
This doesn't imply that, it just says that if users want more help regarding where to find the required .yml CloudFormation template, they should consult AWS themselves. See:

> You will need it in order to complete the CUR Athena integration.

I don't think we treat this as optional at all

**Comment by chipzoller** [comment]
What I'm suggesting is the last sentence, rather than saying "see this AWS doc" stating, in no uncertain terms, that the procedure outlined in that doc must be followed once you have the CFT in hand. The way it's worded does not make this clear, and, in fact, when I went through this process myself with a fresh AWS account I was at an impasse because of it.

**Comment by bstuder99** [comment]
We've had this in the doc for a while. Does this need to be updated/corrected?

> Athena is technically optional for AWS cloud integration, but as a result, Kubecost will only provide unreconciled costs (on-demand public rates).

**Comment by chipzoller** [comment]
No, it's accurate technically, but for all intents and purposes Athena is required to see the true Kubecost value.
