### ISSUE TITLE
[Enhancement] AWS/EKS Optimized logic

### ISSUE THREAD

**Issue by chipzoller** [kubecost/docs#1028]
### Description

Adding a graphic to show how Kubecost determines if an installation is considered AWS/EKS Optimized or Free.

![image](https://github.com/kubecost/docs/assets/29008123/b0995666-0eef-48d2-9961-f26df62647a0)

cc @kwombach12 and @webb

**Comment by bstuder99** [comment]
Is there a user ticket/Slack thread you can link to about this issue?

**Comment by bstuder99** [comment]
Just need to clarify these statements. Do these revisions sound right?:
* Is cost-model from ECR > Is Kubecost cost-model deployment running in AWS ECR?
* Are all clusters for past 2 hours of type AWS? > Are all clusters running in this environment for the last 2 hours AWS clusters?
Curious why we would need to determine this, isn't this just determined by whether the user performed the standard free install or the EKS Integration?

**Comment by chipzoller** [comment]
> Is there a user ticket/Slack thread you can link to about this issue?

No, this is internal logic change that isn't tied to a documented problem.

> Just need to clarify these statements.
>>Is cost-model from ECR > Is Kubecost cost-model deployment running in AWS ECR?

"Running" isn't applicable here. The check determines if the image is pulled from ECR so maybe "Is the cost-model image from ECR?" is better.

>> Are all clusters for past 2 hours of type AWS? > Are all clusters running in this environment for the last 2 hours AWS clusters?
Curious why we would need to determine this, isn't this just determined by whether the user performed the standard free install or the EKS Integration?

Clarification accepted. It is needed to determine if they're applicable for the EKS optimized license and involves environmental checks during runtime, not how the installation was performed.

**Comment by bstuder99** [comment]
Ok, thanks for the breakdown. I'll add this into the existing PR #1041
