### ISSUE TITLE
[Enhancement] Update references to `AthenaCURBucket` to just `CURBucket`

### ISSUE THREAD

**Issue by chipzoller** [kubecost/docs#1029]
### Description

[Here ](https://github.com/kubecost/cloudformation/blob/master/kubecost-single-account-permissions.yaml#L7) and [here](https://docs.kubecost.com/install-and-configure/install/cloud-integration/aws-cloud-integrations#my-cur-exists-in-the-same-account-as-kubecost-or-the-management-account) this value is (incorrectly) called `AthenaCURBucket` when it isn't...it's the S3 bucket which holds the CUR and is not related to the secondary bucket for the Athena results. A related change was made by @srpomeroy in #1027, but further clarification in the CFT and docs is needed.

**Comment by bstuder99** [comment]
Sounds like the original change needs to be made to the cloudformation template so the docs can properly describe the value. Why do we call this value `AthenaCURBucket` instead of something like `S3CURBucket`?

**Comment by chipzoller** [comment]
The change should be made in both places, I just include the CFT here for completeness. I do not know why the variable was named that.
