### ISSUE TITLE
[Enhancement] update gcp cloud integration guides

### ISSUE THREAD

**Issue by jessegoodier** [kubecost/docs#1061]
### Description

We should be recomending this method for GCP integration: https://github.com/kubecost/cost-analyzer-helm-chart/blob/fb3f4892f76266735faa50e45605738abe4432e2/cost-analyzer/templates/_helpers.tpl#L1351

**Comment by jessegoodier** [comment]
thank you @chipzoller !

**Comment by chipzoller** [comment]
What is the "correct" structure for the JSON values for GCP? I see conflicting information even in the Helm chart. The values file shows [this](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L3373-L3390) while the helper template shows [this](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/_helpers.tpl#L1357-L1369) (and which gets printed out for users). Which is correct so I can document the right one?

**Comment by chipzoller** [comment]
If the PR I sent is correct, it seems like we need to correct the Helm chart in the section listed [here](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/_helpers.tpl#L1357-L1369). Please let me know if that's right and I'll send that in another PR.
