### ISSUE TITLE
No explanation for crude costs in the Custom pricing section

### ISSUE THREAD

**Issue by kastl-ars** [kubecost/docs#1139]
https://github.com/kubecost/docs/blob/35d28fabdb6682eb009a4bd95adf0a292596e54c/architecture/pricing-sources-matrix.md?plain=1#L65

The screenshot in the "Custom pricing" section has different numbers compared to what is being set in the YAML snippet.

I would really like to see an explanation in the documentation on why the numbers are not used as specified. What is the reason? How is this being calculated?

Example:

- spotCPU is `4.86` in the YAML snippet.
- spotCPU is shown as `4.8586824` in the screenshot

(The CPU cost is off anyway, see #1138)

**Comment by AjayTripathy** [comment]
The configs and screenshots are just samples; they don't need to match each other exactly.
