### ISSUE TITLE
The Cluster Right-Sizing Recommendations  function fails to run

### ISSUE THREAD

**Issue by caiyuanji** [kubecost/docs#1147]
### Description

I added kubecost to the locally deployed k8s cluster and failed to run the ”Cluster Right-Sizing Recommendations“ function with the following output:  Error loading cluster sizing recommendations.  
Is it related to my local cluster hardware configuration?

**Comment by chipzoller** [comment]
For issues regarding support, please open a request at support.kubecost.com.
