### ISSUE TITLE
External costs - AWS master-payer pattern clarifications 

### ISSUE THREAD

**Issue by robertgates55** [kubecost/docs#126]
I've got a master-payer account structure, with subaccounts for eg Dev, QA, Prod, etc. Each cluster in each subaccount runs it's own kubecost cost-analyzer deployment.

Am I right in thinking that the 'external' costs that get pulled in from AWS will be for _all_ accounts (as per the CUR being exported and queried over?). I can see a lot of things in the QA QA1 cluster's 'Assets' view that I presume are from eg Prod.

Is there any way to only see kubernetes_cluster-tagged resources in this view? Or is the idea that the assets view shows everything and you then use switch-cluster to show numbers for a specific one?

gz#770

**Comment by robertgates55** [comment]
Follow-up Q: my cluster is named `qa-qa1` but I see on the assets view `qa-qa1/cluster-one`. What `kubernetes_cluster` tag should I be using in AWS to associate resources to this cluster?
![image](https://user-images.githubusercontent.com/7437497/132325783-4adfa185-2409-43b9-985d-357622ede1de.png)

**Comment by kbrwn** [comment]
@robertgates55 Yes, assets view will show all aws resources from the cost and usage report. You should be able to filter in assets to isolate to a single cluster by name. So in this case you'd pass "cluster-one".

**Comment by robertgates55** [comment]
Really? Where does the `cluster-one` come from though? I don't have any clusters called 'cluster-one' - the cluster is called `qa-qa1`?

(if I labelled it as `cluster-one` I presume that in my prod-prod1 instance of cost-analyzer I'd end up with `prod-prod1/cluster-one` also pulling that in, for example...)

**Comment by kbrwn** [comment]
@robertgates55 How are you defining the cluster name? 'cluster-one' is the default value that used by this chart for cluster identification. You can modify this [value](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L378) to provide unique names for each cluster.

**Comment by robertgates55** [comment]
In my helm values.yaml, I'm defining this:
```
kubecostProductConfigs:
  clusterName: qa-qa1
...
```

What is that name vs the `prometheus.server.global.cluster_id` (which is set to `cluster-one`)?

**Comment by kbrwn** [comment]
@robertgates55 `clusterName` is used to update the UI/frontend. cluster_id in the prometheus section is used for associating metrics with a cluster.

**Comment by kbrwn** [comment]
@robertgates55 do you need any more help with this?
