### ISSUE TITLE
The currrent documentation website has limited discoverability/support for hierachal documentation

### ISSUE THREAD

**Issue by obowersa** [kubecost/docs#165]
Ref: https://github.com/kubecost/cost-model/issues/781

This might need split into two issues.

The initial question I had was: For documentation ( such as how to integrate kubecost's alerting with MS Teams) where in the documentation hierachy should this go. I think at the moment it would either be in the alerting.md file. 

This has lead to a larger question on my side: Is the architect theme being used for documentation suitable for a growing documentation base ?

Looking at the docs as it stands they seem to be hard to discover/search from the documentation website. I think this is due in part due to the flat structure of the architect theme. When compared to themes more aimed at documentation ( docsy, doks, etc ) architect doesn't natively support a hierachal navigation approach and instead relies on a simple side bar + links within existing pages. Would there be any interest in trying a different structure for the documentation to aid with discoverability? 

gz#1306

**Comment by srpomeroy** [comment]
@obowersa We are in the progress of moving our docs here: https://guide.kubecost.com/hc/en-us/categories/1500002121181-Documentation
Have you seen this site yet?

We are very much iterating on the design as we go. We've also begun to implement some hierarchy in our docs at the new Guide site. And as mentioned in the other issue, @kbrwn will have some thoughts on the best place to add the MS Teams information you are looking to build. As an example, the current alerting documentation is under the `Using Kubecost` section.

**Comment by obowersa** [comment]
That's awesome! I hadn't seen the guide.kubecost page, was mainly basing it on the docs.kubecost setup. Thanks for the info, I'll close this issue off
