### ISSUE TITLE
Set up docs to guide redirect

### ISSUE THREAD

**Issue by kbrwn** [kubecost/docs#172]
@AjayTripathy suggested I create an issue to request an update the docs.kubecost.com dns entry to the redirect server IP (34.83.246.98).

**Comment by dwbrown2** [comment]
Sweet, you feel all ready on your end? Any known issues to be aware of?

My only specific question is what's the process for making a contribution? Will this now pick up changes to master in this repo?

**Comment by dwbrown2** [comment]
Assigning back to you Kyle for this quick questions.

**Comment by kbrwn** [comment]
@dwbrown2 The process for making a contribution is the same. The only difference is master branch needs to be replaced will be replaced by main branch as default in this repo and all commits need start using main going forward. This is to follow the 2022 github repo standards as well which prefer main to master for default branch. 

When a new push to main branch occurs a Github Action will be kicked off that uploads documentation to guide.kubecost.com: 

https://github.com/kbrwn/docs-1/runs/5147029536

**Comment by dwbrown2** [comment]
Boom! That's awesome. And sounds like no other known limitations with rendering markdown? 

@AjayTripathy do you want to switch default branch and then I can redirect DNS? If so, give me a heads up before you do so that we can coordinate.

**Comment by kbrwn** [comment]
@dwbrown2 The only current limitation is <details> tags which have to use HTML instead of markdown inside the <details></details> tag to be formatted correctly.

**Comment by AjayTripathy** [comment]
We're ready to do this, no need to switch the branch right now. Please redirect the DNS.

**Comment by dwbrown2** [comment]
@AjayTripathy mentioned he was going to review getting links like http://34.83.246.98/saved-reports to function

**Comment by AjayTripathy** [comment]
Kyle's on it!

**Comment by dwbrown2** [comment]
Awesome! @AjayTripathy did you say that you want to review relative images links?

We're now getting close to a big launch announcement... how about we aim to make this transition soon after if you're good on images?

**Comment by AjayTripathy** [comment]
Fixed up relative image links except for a few that are out of date anyway. I'm ready to launch this.

**Comment by AjayTripathy** [comment]
Searched all ".pngs" and made sure they were either specified by an absolute path or irrelevant/outdated.

**Comment by kirbsauce** [comment]
@dwbrown2 , can we get the redirect done so we can close this out?  As I understand you are the only one w/access to the button.

**Comment by dwbrown2** [comment]
@stacy-tumarkin would you be able to do this transfer? My vote is that we do it towards the end of the week when we have less traffic.

**Comment by stacy-tumarkin** [comment]
On it! @kbrwn @kirbsauce what testing do we need to do once it's live? When (e.g. a specific time) do you want the redirect in place ideally so we're all available to test?

**Comment by kbrwn** [comment]
@stacy-tumarkin The redirect server at 34.83.246.98 is live. You can test the redirects by visiting 34.83.246.98/doc-name (ie 34.83.246.98/saved-reports or 34.83.246.98/saved-reports.html). Changing the DNS A Record for docs.kubecost.com to this IP will mean that docs.kubecost.com/saved-reports will hit the redirect server and redirect to the corresponding guide page. This can be tested by visiting a docs.kubecost.com link after making the DNS change.

**Comment by kirbsauce** [comment]
thanks @kbrwn.  Sounds pretty straightforward but I'm happy to be online as a tester.

**Comment by stacy-tumarkin** [comment]
So is now a good time to get the redirect going?

**Comment by dwbrown2** [comment]
It appears this now done?

Why are we not doing a permanent redirect from docs.kubecost.com and preserving the URL? Current approach may have negative seo impact and the URLs are less human readable.

**Comment by kirbsauce** [comment]
@dwbrown2 , I get redirected to "guide" when going to "docs" from an incognito window.

**Comment by dwbrown2** [comment]
Yeah, I thought we were point docs.kubecost.com to a new IP and therefore keeping our existing subdomain and user-friendly URLs...

**Comment by stacy-tumarkin** [comment]
@kbrwn was having issues with TLS, this is a temporary workaround until he gets the permanent solution in place Monday.

**Comment by kbrwn** [comment]
this is all done! closing!

**Comment by kirbsauce** [comment]
awesome!
