### ISSUE TITLE
Clarification on spot data feed configuration

### ISSUE THREAD

**Issue by dvdmuckle** [kubecost/docs#19]
Hi there, I'm trying to get the spot instance data feed working for a deployment of Kubecost, and I've run into trouble getting it to work fully, part of my confusion lying in how the docs are formatted. For context. this is on a 1.16.0 cluster in AWS, and we are using kiam in order to grant access, rather than access keys and secrets. The IAM role granted to Kubecost is overly permissive in terms of S3, so I don't believe that to be the problem. 

Is the Prometheus metric `node_total_hourly_cost` a trustworthy sign that the spot feed is working? I did notice the metric is available before configuring the spot feed, but after configuring the spot data feed, the metric dropped significantly, which makes me think things might be working.

There's also the issue that I don't see the following logs at all:
```
I1104 00:21:02.905327       1 awsprovider.go:1397] Found spot info {Timestamp:2019-11-03 20:35:48 UTC UsageType:USE2-SpotUsage:t2.micro Operation:RunInstances:SV050 InstanceID:i-05487b228492b1a54 MyBidID:sir-9s4rvgbj MyMaxPrice:0.010 USD MarketPrice:0.004 USD Charge:0.004 USD Version:1}
I1104 00:21:02.922372       1 awsprovider.go:1376] Spot feed version is "#Version: 1.0"
```
However I do see these logs:
```
I0518 17:40:32.750949       1 awsprovider.go:1804] Found 0 spot data files from yesterday
I0518 17:40:32.765787       1 awsprovider.go:1813] Found 2 spot data files from today
```
After crawling through the code a bit, it appears the logs about finding spot data files confirm that Kubecost is able to read from the S3 bucket. The numbers here are also accurate to the files in the bucket itself. Shortly after the above logs, I also see:
```
2020/05/19 03:19:43 error getting addresses: EnvAccessKeyNotFound: AWS_ACCESS_KEY_ID or AWS_ACCESS_KEY not found in environment
2020/05/19 03:19:43 error getting disks: EnvAccessKeyNotFound: AWS_ACCESS_KEY_ID or AWS_ACCESS_KEY not found in environment
```
Which I believe to be generated by the AWS SDK. So, while kiam and the associated role seem to be working, something else looks to be trying to use environment variables that don't exist.

With that in mind, is there something missing in the docs, or something I'm missing in the docs, to get the spot data feed working?

**Comment by AjayTripathy** [comment]
Hi @dvdmuckle, seems like the spot data feed has been correctly set up. Those log statements are from an optional module that can be configured to find abandoned load balancers and disks. We will add that to our spot documentation and make sure those logs are less confusing in a future release. Sorry for the confusion.

**Comment by dvdmuckle** [comment]
Awesome, thank you! To be clear, my confusion stemmed from not seeing the confirmation logs noted in the docs, so I wasn't sure if everything was completely functional.

**Comment by dvdmuckle** [comment]
One final question, does the spot label value need to be set, or can Kubecost rely on empty labels? We label spot nodes with a label that has an empty string as a value.

**Comment by AjayTripathy** [comment]
That should work-- we haven't tested an empty string in a while. Since node_total_hourly_cost seems to have dropped, I'd say that it works, but let me know if we need to test that more closely.

**Comment by dvdmuckle** [comment]
Sounds good! I'll make sure to let you know if we run into any more issues.
