### ISSUE TITLE
New docs site footer styling is off 

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/docs#192]
It looks like the background color is wrong.

![image](https://user-images.githubusercontent.com/298359/156858571-b624b0ce-c22c-4b8c-be2b-7886c4b2a17d.png)

When you hover on icons they are no longer visible. 

@kbrwn are you best to tackle?

**Comment by kbrwn** [comment]
@stacy-tumarkin might be better equipped for this one although I can take a try at it if you like.

**Comment by dwbrown2** [comment]
SG, @stacy-tumarkin let me know how I can help. Looks like it's only happening at https://guide.kubecost.com/hc/en-us and not on other pages...

**Comment by kbrwn** [comment]
@stacy-tumarkin I redirected docs.kubecost.com directly to the welcome doc temporarily to get around this for now. Interesting that it only happens at https://guide.kubecost.com/hc/en-us directly.

**Comment by dwbrown2** [comment]
@kbrwn that def looks better! but even there the icons change to the bg color on hover

**Comment by AjayTripathy** [comment]
Assigned to @teevans for further triage

**Comment by teevans** [comment]
![image](https://user-images.githubusercontent.com/3982846/164300885-75b05681-9a32-4672-8b9b-d59c4355ca04.png)

Think I got this one fixed. @dwbrown2 ?

**Comment by dwbrown2** [comment]
LGTM!
