### ISSUE TITLE
The order of navigation links should be improved

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/docs#193]
We should at re-ordering these links. See examples below.

* Spot guide is probably not the best starting point after our Welcome guide. 
![image](https://user-images.githubusercontent.com/298359/156858833-9b7d0cd4-04a5-4d6a-a52d-179d6b9a0945.png)

* Installing Kubecost with Rafay is not the first link we would want to show under `Setup`.
![image](https://user-images.githubusercontent.com/298359/156858718-972c0506-eb9a-468e-be82-c2a33ac26745.png)

**Comment by dwbrown2** [comment]
@kbrwn what's the best way to get these updated?

**Comment by kbrwn** [comment]
@dwbrown2 If you post an order here that you'd like I can update it.

**Comment by dwbrown2** [comment]
Cool, happy to make some suggestions but also totally open to debating/discussing!

**Comment by dwbrown2** [comment]
And just to clarify are all docs pages in the navigation panel?

**Comment by kbrwn** [comment]
@dwbrown2 All markdown docs that are on the `main` branch of this repo are uploaded to help center and are available in the navigation.

**Comment by dwbrown2** [comment]
@kbrwn I've started this doc to list what I think could be good top N items under these categories... https://docs.google.com/document/d/1YOkNpRWtXhmetulucovR5ypqp7Ahgm4jXvRyXMUfO08/edit#

are you ok to run with it from here?

**Comment by dwbrown2** [comment]
@kbrwn anything else you need on this one?

**Comment by kbrwn** [comment]
@dwbrown2 I plan to update the ordering this week. The the future I plan to make ordering configurable via metadata string: https://github.com/kubecost/zd-docs-uploader/issues/5 In an update this week new docs will be placed at the bottom of the section rather than the top.

**Comment by dwbrown2** [comment]
Sg, don't feel to strongly about adding another var, as I wouldn't expect these to change too too often.

**Comment by dwbrown2** [comment]
@kbrwn were we able get these updated?

**Comment by AjayTripathy** [comment]
Assigned to @teevans for further triage.

**Comment by teevans** [comment]
@dwbrown2 - I took a first stab at this - Let me know what you think [Link here](https://guide.kubecost.com/hc/en-us/articles/4407601821207-Installing-Kubecost)

**Comment by dwbrown2** [comment]
Looks like a huge improvement to me! I'm good to call done unless there's anything you want feedback on.

**Comment by teevans** [comment]
No sir! Closing.
