### ISSUE TITLE
Should we remove sign in link from new docs site?

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/docs#199]
I'm pretty sure this header button isn't relevant to our users. If so, can we remove from this page? 

![image](https://user-images.githubusercontent.com/298359/157937792-3052dbae-e54c-49f3-9b71-f1fd314833c7.png)

https://guide.kubecost.com/hc/en-us/articles/4407595950359-Welcome#getting-started-1

**Comment by dwbrown2** [comment]
Good to know, didn't realize. Given that do we think it's given the right amount of visual prominence? Seems fine to me...

**Comment by kbrwn** [comment]
@dwbrown2 I am happy to adjust it if you prefer it smaller or in another place! Let me know.

**Comment by dwbrown2** [comment]
Defer to you guys! Don't feel strongly here.

**Comment by teevans** [comment]
@dwbrown2 - Have you thought any more on this? I'd say we can keep it for now, but if you know something I don't feel free to share

**Comment by dwbrown2** [comment]
Yeah, I'm not too concerned about keeping for now. Think it's low priority.
