### ISSUE TITLE
Updated terminology and clarify aws cloud integration doc

### ISSUE THREAD

**Issue by kbrwn** [kubecost/docs#200]
"Master Payer" is now "Management Account" according to AWS: https://docs.aws.amazon.com/organizations/latest/userguide/orgs_getting-started_concepts.html

Member accounts have [access to the CUR](https://aws.amazon.com/about-aws/whats-new/2020/12/cost-and-usage-report-now-available-to-member-linked-accounts/) if the management account allows it and do not need management account IAM permissions for access or to enable. This set up is not well reflected in the "Setting up IAM permissions" section: 

```
My kubernetes clusters all run in the same account as the master payer account.
My kubernetes clusters run in different accounts from the master payer account

My Kubernetes clusters run in the same account as the master payer account
My Kubernetes clusters run in different accounts
````

Maybe these options should reflect the location of the CUR rather than the location of the cluster?

**Comment by bstuder99** [comment]
Corrected via GitBooks
