### ISSUE TITLE
Document queries run by ETL tool

### ISSUE THREAD

**Issue by ErnestG4** [kubecost/docs#203]
It is currently necessary to reference source code in order to determine the queries run by the ETL tool. 

A document containing these queries for various platforms may be valuable to users. 

It can be referenced as a footnote in the existing ETL docs.

**Comment by dwbrown2** [comment]
+1 but also know these can be hard to keep in sync. What do you think by starting with a direct link to source code in docs and then evolving if users need more?

**Comment by ErnestG4** [comment]
Sounds good!

**Comment by dwbrown2** [comment]
Cool, want to run with this one or can we help get you a hand?
