### ISSUE TITLE
External cost tag is incorrect in Azure out of cluster costs

### ISSUE THREAD

**Issue by theadzik** [kubecost/docs#214]
Tags got italicized by mistake on pages:

* https://guide.kubecost.com/hc/en-us/articles/4407595936023-Adding-Azure-Out-of-Cluster-Cluster-Costs-into-Kubecost

* https://guide.kubecost.com/hc/en-us/articles/4407596810519-AWS-Out-of-Cluster-

We have kubernetes_label_NAME instead of 'kubernetes_label_NAME'

gz#1635

**Comment by kbrwn** [comment]
@theadzik Thanks for your contribution. I have merged your pr and the docs have been updated.
