### ISSUE TITLE
Metrics Issue with Prometheus making it not work 

### ISSUE THREAD

**Issue by VishInventor** [kubecost/docs#23]
Hi there. 

It is not working for me. I installed using helm 3 on a 3 nodes cluster with K8s version 1.18.4. 

When I access the localhost link, it shows the below error at the end of the page:- 
Unable to establish a connection with Prometheus at http://localhost:9090/api

Deployment kubecost-prometheus-server has the issue. Its pods is not running. It shows persistent volume claim error. 

![image](https://user-images.githubusercontent.com/48930880/87259402-002ec580-c4a3-11ea-96d3-14063cf8d405.png)

Because, of above even Grafana dashboard does not show up the metrics. 

Please let me know how we can make it work. Thanks.

**Comment by dwbrown2** [comment]
What is the actual error you are seeing? It sounds like you either need to disable PVs or have Prometheus attach to a PV.

**Comment by VishInventor** [comment]
It is not able to pull the details from the cluster. localhost link shows nothing. I think issue is Prometheus server pod deployment is not working and hence there is no metrics. I would have thought helm would put all the required configs in place. Not sure what to do.

**Comment by dwbrown2** [comment]
Yeah, I can't help much without seeing the error. it sounds like this could be your issue though: http://docs.kubecost.com/troubleshoot-install.html#persistent-volume
