### ISSUE TITLE
guide.kubecost.com starts on Windows Node Support instead of a proper Welcome page

### ISSUE THREAD

**Issue by mattray** [kubecost/docs#244]
https://guide.kubecost.com/ ends up on https://guide.kubecost.com/hc/en-us/articles/6152374933655-Windows-Node-Support
A better landing page would probably be https://guide.kubecost.com/hc/en-us/articles/4407595950359-Welcome

**Comment by kbrwn** [comment]
This occurred after reordering of sections and docs done via Admin console without any testing for how upload code would be effected. Currently when a new doc gets uploaded it takes the first position in the section rather than the last. I plan to fix this by adding the zendesk api position parameter to this struct: https://github.com/kubecost/zd-docs-uploader/blob/main/main.go#L56-L63 and setting default to last position. 

I fixed the guide.zendesk.com site to point to Welcome again for now but if a new doc is uploaded to the Setup section or if another section is placed above the Setup section via admin console the main page will change again.

**Comment by dwbrown2** [comment]
Thanks for reporting Matt and for fixing Kyle! 

> I fixed the guide.zendesk.com site to point to Welcome again for now but if a new doc is uploaded to the Setup section or if another section is placed above the Setup section via admin console the main page will change again.

Did you mean https://guide.kubecost.com/ in this section? 

cc @teevans

**Comment by kbrwn** [comment]
@teevans @dwbrown2 I have added the needed position parameter to the createArticle function. New docs will now upload to the bottom of the section on first upload! Not sure why it didn't work for you...I plan to expand this to the updateArticle function to allow for reordering via metadata next. 

If we want the "General" section to be the first. I propose we move the "Welcome" doc to this section and set it to the top position. If we are comfortable with "Setup" first I believe this can be closed.

**Comment by dwbrown2** [comment]
I believe @AjayTripathy created this particular article. Adding him just in case he did something special :)

**Comment by kbrwn** [comment]
@dwbrown2 I do not believe Ajay did anything abnormal. He added the .md file to this repo with no metadata so it was uploaded to general at the top of the section. With the new code this doc would be uploaded to the bottom position in the General section.

**Comment by teevans** [comment]
This may help actually - Looks like the position parameter is a sortable position on the API, but I didn't find any documentation surrounding its use on the actual GUI. Also looks like the guide ordering is limited to a few parameters judging by this screenshot. 

<img width="530" alt="image" src="https://user-images.githubusercontent.com/3982846/170305013-745426c9-87b3-4aaa-833d-d275ae7d56a6.png">

@kbrwn - Care to test an upload with your new code and see if the position parameter acts as expected?

**Comment by kbrwn** [comment]
@teevans I tested my code: https://guide.kubecost.com/hc/en-us/articles/6322872179223-Test
<img width="251" alt="Screen Shot 2022-05-25 at 10 05 33 AM" src="https://user-images.githubusercontent.com/4100493/170307402-d4508816-c089-471c-bbee-067420e02c9d.png">

**Comment by mattray** [comment]
Sounds great, thanks!
