### ISSUE TITLE
The navbar is overflowing

### ISSUE THREAD

**Issue by iswarmondal** [kubecost/docs#263]
On the landing page of Kubecost.com, the navigation bar is overflowing to the x-axis on mobile phone browsers.
It is causing really bad UX.

If you want I could create a PR for this.

gz#1960<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1960'>Zendesk ticket #1960</a>)</i>

**Comment by dwbrown2** [comment]
Thanks for reporting. Is this related to the kubecost application, kubecost.com or something else?

**Comment by dwbrown2** [comment]
@AdamStack18 noticed this was missing triage tag

**Comment by iswarmondal** [comment]
> Thanks for reporting. Is this related to the kubecost application, kubecost.com or something else?

Yeah, It's related to Kubecost.com, the website.
The problem is happening for the mobile web browsers.

**Comment by dwbrown2** [comment]
Any chance you can send a screenshot or more info on device/resolution? I'm not able to repro:

<img width="541" alt="image" src="https://user-images.githubusercontent.com/298359/173487591-506802aa-112a-49ec-9ca1-f989abfe2386.png">

**Comment by iswarmondal** [comment]
Yeah sure,
#### This is on the iPhone XR preset (414px * 896px)
#### I tried on my phone and the same thing is happening on an actual phone also.

![image](https://user-images.githubusercontent.com/73457704/173488090-04be4564-813b-44b2-8738-f919c0b7518b.png)

**Comment by AdamStack18** [comment]
@iswarmondal Thanks for your help troubleshooting this issue.  Not able to repo on my side as well. Could you share the web browser you are using?

**Comment by AdamStack18** [comment]
> @AdamStack18 noticed this was missing triage tag

@dwbrown2 Thanks for the heads up. The bot PR was most likely merged after this issue was created.

**Comment by dwbrown2** [comment]
I'm able to repro! @teevans this property has much more mobile traffic so might be worth exploring a fix soon. Let us know what you think. 

<img width="601" alt="image" src="https://user-images.githubusercontent.com/298359/173871367-74ccf93f-8083-4b11-aa43-0965a1fa9723.png">

**Comment by iswarmondal** [comment]
> I'm able to repro! @teevans this property has much more mobile traffic so might be worth exploring a fix soon. Let us know what you think.
> 
> <img alt="image" width="601" src="https://user-images.githubusercontent.com/298359/173871367-74ccf93f-8083-4b11-aa43-0965a1fa9723.png">

If you want I can take a shot at this and create a PR of the fix

**Comment by teevans** [comment]
Hey @iswarmondal - I'm working on a fix for this right now! Thanks so much for pointing this out!

**Comment by iswarmondal** [comment]
@teevans sure.

**Comment by Adam-Stack-PM** [comment]
Closing out. Fixed in https://github.com/kubecost/kubecost-website/pull/42
