### ISSUE TITLE
Upgrade from 1.66.0 to 1.67.0 is having issue

### ISSUE THREAD

**Issue by gouravsw** [kubecost/docs#27]
Hello, I am trying to upgrade kubecost from 1.66.0 to 1.67.0 in a cluster where Kubernetes version is 1.13.

As mentioned in document, https://github.com/kubecost/docs/blob/master/thanos-upgrade.md I have done the changes for secret and deployed the same. After that upgrading to version 1.67.0 using helm. 
Thanos is getting upgraded to version 0.15.0. 

But while upgrade pod cost-analyzer is in pending state. And below is the message while describing the pod.  Could you please help on the below issue?

`  Type     Reason             Age                From                Message
  ----     ------             ----               ----                -------
  Normal   NotTriggerScaleUp  74s                cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added): 2 Insufficient cpu, 6 node(s) had taints that the pod didn't tolerate, 8 node(s) **had no available volume zone**
  Normal   NotTriggerScaleUp  64s                cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added): 8 node(s) had no available volume zone, 2 Insufficient cpu, 6 node(s) had taints that the pod didn't tolerate
  Normal   NotTriggerScaleUp  54s                cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added): 2 Insufficient cpu, 8 node(s) had no available volume zone, 6 node(s) had taints that the pod didn't tolerate
  Warning  FailedScheduling   10s (x4 over 77s)  default-scheduler   persistentvolumeclaim "costing-cost-analyzer-db" not found
  Normal   NotTriggerScaleUp  3s (x5 over 44s)   cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added): 8 node(s) had no available volume zone, 6 node(s) had taints that the pod didn't tolerate, 2 Insufficient cpu`

While upgrading it is creating a new PVC and as old PVC is also there, so I assume it is confused to use which PV/PVC.

`NAME                             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE

costing-cost-analyzer            Bound    pvc-64ef5f3d-cb78-11ea-b62b-0a6a682c3ebc   1Gi        RWO            ebs-general-gp2   **90d**

costing-cost-analyzer-db         Bound    pvc-0a814698-12e5-11eb-b072-025920e6cffc   32Gi       RWO            ebs-general-gp2   **12m**`

**Comment by AjayTripathy** [comment]
Hi @gouravsw , can you upgrade to 1.67.3 and let us know if this error persists? We moved back to using just a single PV by default to prevent these errors.

**Comment by dwbrown2** [comment]
Here's more info on our storage too: https://github.com/kubecost/docs/blob/master/storage.md

Let me know if you have questions on that doc.

**Comment by gouravsw** [comment]
@dwbrown2 @AjayTripathy Thank you for the inputs. I will try with the latest version of 1.67.3

**Comment by gouravsw** [comment]
@AjayTripathy It worked with you any issue. Upgrade was smooth. Thank you 👍 , Issue can be closed.

**Comment by dwbrown2** [comment]
Glad to hear, @gouravsw! Please reach out at any time if we can help with anything else.
