### ISSUE TITLE
Wrong cost computation for GPU node

### ISSUE THREAD

**Issue by kinihun** [kubecost/docs#28]
Hello,
I have a single Azure Standard_NC6 instance in one of my nodepools, it's showing a daily usage cost of over $900. That's more than the monthly cost for that instance.
![image](https://user-images.githubusercontent.com/18234695/96749004-2e854080-13c2-11eb-9528-16c2e6bbc00c.png)

**Comment by dwbrown2** [comment]
@kinihun saw you closed this, and just wanted to make sure you are good to go. Let us know if you need anything.

**Comment by kinihun** [comment]
@dwbrown2 
it's still an issue, I created it under cost-analyzer
https://github.com/kubecost/cost-analyzer/issues/3
