### ISSUE TITLE
Confusion about storage requirements

### ISSUE THREAD

**Issue by bwhaley** [kubecost/docs#290]
The storage configuration documentation states the following:

> Where ingested samples can be measured as the average over a recent period, e.g. sum(avg_over_time(scrape_samples_post_metric_relabeling[24h])). On average, Prometheus uses around 1.5-2 bytes per sample. So ingesting 100k samples per minute and retaining for 15 days would demand around 40 GB. It's recommended to add another 20-30% capacity for headroom and WAL. More info on disk sizing [here](https://prometheus.io/docs/prometheus/latest/storage/#operational-aspects).

Is my arithmetic wrong, or does the example actually suggest 4GB is needed rather than 40GB?

2bytes per sample * 100k samples per minute * 15 days (21,600 minutes) = 4320000000 bytes = 4.32GB

gz#2123<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2123'>Zendesk ticket #2123</a>)</i>

**Comment by keithhand** [comment]
Hi @bwhaley, I believe that math adds up to me as well. Let me submit a PR and get it in front of engineering to get another opinion and possibly get this tweaked. Thank you!
