### ISSUE TITLE
AWS Spot Instance Not Showing

### ISSUE THREAD

**Issue by frankjwk** [kubecost/docs#299]
Hi there, about a week ago I configured the AWS integration and permissions. I was able to view which EKS nodes were spot instances and their different hourly rate, but recently I could not view these. Could someone look into this?

gz#2146<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2146'>Zendesk ticket #2146</a>)</i>

**Comment by kirbsauce** [comment]
Hi @frankjwk.  Thanks for posting!  We'll dig into this right away.

**Comment by dwbrown2** [comment]
@kirbsauce any insights that you can share? Let us know how we can help.

**Comment by zorrobyte** [comment]
Hey @frankjwk ! I'd love to help to get to the bottom of this; could you share what version you are running?

Note that we had some pretty big changes in our latest release: 
https://github.com/kubecost/cost-analyzer-helm-chart/releases/tag/v1.95.0

Would you mind giving it a go and let us know?

**Comment by bstuder99** [comment]
Checking in on this after some time, did we get a resolution on this?

**Comment by bstuder99** [comment]
I'm closing the issue due to lack of activity/response, feel free to reopen if the issue persists.
