### ISSUE TITLE
How to Set up CUR integration in AWS Gov Cloud

### ISSUE THREAD

**Issue by mmurph3** [kubecost/docs#359]
[AWS S3 CUR Integration.pdf](https://github.com/kubecost/docs/files/9618950/AWS.S3.CUR.Integration.pdf)
Need documentation around this process

IAM Roles Anywhere is NOT supported for non AWS workloads: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_non-aws.html

The CUR would need to be created in the commercial account and transferred over to an s3 bucket in govcloud so kubecost can pull the data correctly.

This can be achieved various ways through awscli, govcloud import tool, s3 sync, datasync, lambda, etc.

The high level concept is to pull the data from the s3 bucket down to an intermediary then upload it to an s3 bucket in aws govcloud. 

Public sector customers want clearer direction on how to achieve this and how kubecost would be set up to run in govcloud. One approach for setting up kubecost in govcloud is the s3 CUR integration (attached) after it is transferred from commercial to govcloud. 

s3 sync
https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html

datasync
https://docs.aws.amazon.com/managedservices/latest/userguide/data-sync.html

govcloud import tool
https://aws.amazon.com/blogs/publicsector/gov-cloud-import-tool-how-to-transfer-information-between-identity-boundaries/

**Comment by srpomeroy** [comment]
I don't unfortunately. We've been having a discussion on [Slack](https://kubecost.slack.com/archives/G01MN4R06MB/p1663705282256009).

We are planning on setting up a GovCloud account to test with.

**Comment by kc-creynold** [comment]
This is a priority.  GovCloud is heavily used by Public Sector.  I am working on getting us AWS GovCloud access and Azure Gov access.  This will take a while as we have to register with DECCS prior to getting GovCloud access.

**Comment by AjayTripathy** [comment]
@kc-creynold can we take our best stab at documentation until we can get the account set up?

**Comment by kc-creynold** [comment]
yeah we can take a rough stab

**Comment by mmurph3** [comment]
From customer:

For the spot feed, the subscription also has to be created in the public mgmt account.  In public, I created a [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) for kubecost to access the s3 bucket.  This obviously wouldn't work for govcloud to access a s3 bucket in public.  What is the recommended way to access the spot feed data in public from govcloud?

**Comment by srpomeroy** [comment]
>From customer:
>For the spot feed, the subscription also has to be created in the public mgmt account. In public, I created a [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) for kubecost to access the s3 bucket. This obviously wouldn't work for govcloud to access a s3 bucket in public. What is the recommended way to access the spot feed data in public from govcloud?

Adding context from [Slack](https://kubecost.slack.com/archives/G01MN4R06MB/p1664985016156949):
>Spot data feeds are an account level setting, not a payer level.
>So every AWS Account will have its own spot data feed.
>Spot data feed is not currently available in GovCloud.
