### ISSUE TITLE
Document Write VS Read Routes in Kubecost

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/docs#360]
As titled. Here's the enumeration of routes and what is marked as write. https://github.com/kubecost/kubecost-cost-model/blob/develop/pkg/auth/samlauth.go#L269

**Comment by bstuder99** [comment]
Appears to be completed in https://docs.kubecost.com/install-and-configure/advanced-configuration/user-management:
> editor: Role can change and build alerts and reports, but cannot edit application settings and otherwise functions as read-only.
