### ISSUE TITLE
New docs are failing to publish

### ISSUE THREAD

**Issue by michaelmdresser** [kubecost/docs#363]
We are unable to publish new docs to guide.kubecost.com right now due to expired credentials. Docs that already exist are still receiving updates.

See e.g. https://github.com/kubecost/docs/actions/runs/3113402788

Technical details of the issue explained here: https://github.com/kubecost/zd-docs-uploader/issues/7. Raising an issue here because this repo has more visibility.

@bstuder99 we were talking about this earlier.

@Adam-Stack-PM FYI -- we probably need to put eng effort here to find a solution and implement it. There are a few different ways to fix, some quicker than others, but I don't have time to walk through them and pick one.

**Comment by Adam-Stack-PM** [comment]
@srpomeroy, thanks for taking on this issue. Let me know if you need anything.  @michaelmdresser, thanks for the mention and context.
