### ISSUE TITLE
Document all sliders and options on the new allocation page clearly

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/docs#394]
Essentially we want to have clear documentation for every slider on our core cost allocation page clearly defined. I'm envisioning detailed screenshots and samples This would include for example:
1. What are services? https://github.com/kubecost/cost-analyzer-frontend/issues/1179#issuecomment-1284250065
2.  What is idle?
3. How do I make queries for labels
4. How do I query data on a per day basis
...and many more

This task represents a common theme where users don't actually know how the allocation page works and what their various options are.

**Comment by bstuder99** [comment]
Hey Ajay, I'd be able to implement these docs changes as part of a larger overhaul with the webUI release. Could you elaborate more on the sliders you mention?

**Comment by bstuder99** [comment]
I've gone back and tried to be more descriptive with the technical terminology. At the surface of any doc containing UI elements, I we have explained what every feature does, but I definitely can break down this doc into sections based on function as well. For example, beyond basic explanations of the Edit Report button, the doc now explains retrieving data on a per-day basis with a screenshot attached. If there are any other direct support tickets regarding "a common theme where users don't actually know how the allocation page works," I'd love to look over them.
https://github.com/kubecost/docs/blob/main/cost-allocation.md
