### ISSUE TITLE
Document https://github.com/kubecost/kubecost-cost-model/issues/928 under ETL Cloud Storage Backups

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/docs#399]
https://github.com/kubecost/kubecost-cost-model/issues/928 for context and what config options conflict.

**Comment by jcharcalla** [comment]
PR ready for review. https://github.com/kubecost/docs/pull/411

**Comment by bstuder99** [comment]
We currently have this in the troubleshooting section of the ETL Backup page (https://guide.kubecost.com/hc/en-us/articles/4407601811095-ETL-Backup):

"In some scenarios like when using Memory store, setting kubecostModel.etlHourlyStoreDurationHours to a value of 48 hours or less will cause ETL backup files to become truncated. The current recomendation is to keep [etlHourlyStoreDurationHours](https://github.com/kubecost/cost-analyzer-helm-chart/blob/8fd5502925c28c56af38b0c4e66c4ec746761d50/cost-analyzer/values.yaml#L322) at its default of 49 hours."

Is this the same error being discussed in 928?

**Comment by bstuder99** [comment]
Ok, is this resolved?
