### ISSUE TITLE
Document request: reference OpenCost spec in Allocation help docs

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/docs#406]
Proposal is that we should reference the [OpenCost spec](https://github.com/opencost/opencost/tree/develop/spec) as part of the block below.

```
Costs allocations are based on the following:

1. resources allocated, i.e. max of resource requests and usage
2. the cost of each resource
3. the amount of time resources were provisioned

For more information, refer to this [FAQ](https://github.com/kubecost/cost-model#frequently-asked-questions) on how each of these inputs is determined based on your environment.
```

Existing docs link: https://guide.kubecost.com/hc/en-us/articles/4407601807383#cost-metric-1

**Comment by bstuder99** [comment]
Ok. Just because the OpenCost spec is pretty extensive, should we either replace the FAQ link or just add it right after?

**Comment by dwbrown2** [comment]
I'd propose just replace FAQ link with something like, "See the OpenCost Spec for more details...?"

**Comment by bstuder99** [comment]
Done https://github.com/kubecost/docs/commit/4f06decea268cad98e0f2fc01a413cc454a08a9b
