### ISSUE TITLE
Document: Ingress errors on saving UI elements in Azure. 

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/docs#407]
https://kubecost.slack.com/archives/G01MN4R06MB/p1666282046329059?thread_ts=1666199835.677019&cid=G01MN4R06MB

Related: https://github.com/kubecost/kubecost-cost-model/issues/992#issuecomment-1285726991

Let's get all workarounds and theories documented while we work on a potential fix

**Comment by bstuder99** [comment]
It looks like this PR closes this error, I don't think docs are needed here: https://github.com/opencost/opencost/pull/1450
