### ISSUE TITLE
Auditing page is now outdated, no longer supported by WebUI

### ISSUE THREAD

**Issue by bstuder99** [kubecost/docs#415]
I've been updating all articles with WebUI screenshots, and I noticed I cannot recreate these screenshots for an Auditing menu depicted in the article: https://guide.kubecost.com/hc/en-us/articles/4407595925271-Auditing. It looks like this is now outdated, and so the plan should be to either rewrite this for accuracy, or remove it entirely. Thoughts?

**Comment by dwbrown2** [comment]
We've effectively moved the auditing experience into Allocation now that you can drilldown and view rates/costs for each individual container in your infra.

**Comment by bstuder99** [comment]
Ok. Niko was in favor of just scrubbing the article entirely in a separate Slack thread
