### ISSUE TITLE
Document  .Values.kubecostModel.promClusterIDLabel as the correct way to configure the label used to delineate clusters other than cluster_id

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/docs#421]
https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-deployment-template.yaml#L802

Let's document somewhere (perhaps in setup of non-thanos clusters? BYO thanos?) that this is the flag used to configure cluster identifier labels.

**Comment by srpomeroy** [comment]
@AjayTripathy The value of this property should be the label key, correct?
https://github.com/kubecost/cost-analyzer-helm-chart/blob/99fd794608c7b5ed7577a17e9373557badae5849/cost-analyzer/templates/cost-analyzer-deployment-template.yaml

**Comment by bstuder99** [comment]
On it. Currently looking for a good place to put this, but we don't really have any content for cluster management that isn't directly tied to another tool/service. Somewhere in our [Multi Cluster folder](https://docs.kubecost.com/install-and-configure/install/multi-cluster) possibly.

**Comment by srpomeroy** [comment]
My initial thought is the [Prometheus Configuration Guide](https://docs.kubecost.com/install-and-configure/install/custom-prom).
