### ISSUE TITLE
Create an article for CVEs

### ISSUE THREAD

**Issue by bstuder99** [kubecost/docs#425]
At the moment we don't have any documentation for common vulnerabilities and exposures. In response to [this issue](https://github.com/kubecost/kubecost-cost-model/issues/1018), we may seek to create user content on the subject. At the moment I need more clarifying details and will try to rope some subject matter experts into the discussion.

**Comment by michaelmdresser** [comment]
We have nightly image builds which include a post-build vulnerability scan using Aqua's Trivy. (CVE and vuln are _often_ interchangeable words in this context).
- Our documentation on this automation: https://github.com/kubecost/integration-ci-cd#nightly-image-builds
- The specific Trivy GH Action we use: https://github.com/aquasecurity/trivy-action
- Trivy: https://github.com/aquasecurity/trivy

Scan results are posted to a Slack channel every night.

**Comment by michaelmdresser** [comment]
We also scan some/all of our Helm chart dependencies on a nightly basis: https://github.com/kubecost/integration-ci-cd/blob/main/.github/workflows/nightly-scan-dependencies.yaml

**Comment by bstuder99** [comment]
Doc PR listed here https://github.com/kubecost/docs/pull/438
