### ISSUE TITLE
Is Node exporter optional?

### ISSUE THREAD

**Issue by jcharcalla** [kubecost/docs#426]
Our [docs ](https://guide.kubecost.com/hc/en-us/articles/4407595941015-Custom-Prometheus) say node-exporter is optional. We should test this and document what impacts if any result from disabling it (ie: less functionality).

**Comment by dwbrown2** [comment]
This should be documented somewhere but probably worth testing on latest. @AjayTripathy do you know where?

**Comment by jcharcalla** [comment]
I'll look through the docs again to see if I can find any already.

**Comment by jcharcalla** [comment]
So there is this...

https://guide.kubecost.com/hc/en-us/articles/6446286863383-Tuning-Resource-Consumption#disable-or-stop-scraping-node-exporter
"Node-exporter is optional. Some health alerts will be disabled if node-exporter is disabled, but savings recommendations and core cost allocation will function as normal"

And then on this page: https://guide.kubecost.com/hc/en-us/articles/4423256582551-Kubecost-Secondary-Clusters#node-exporter
"You can disable node-exporter and the service account if cluster/node rightsizing recommendations are not required."

To me those descriptions almost conflict "but savings recommendations ... will function as normal" vs "if cluster/node rightsizing recommendations are not required".

I think there is room to improve here by clarifying what features will be unavailable when node-exporter is disabled.

**Comment by bstuder99** [comment]
If we have a list of the key features that aren't accessible when the node exporter is disabled, I can start adding this to the docs.

**Comment by bstuder99** [comment]
I would say it should be added to the Tuning Resource Consumption page, where we already have a section dedicated to the subject
