### ISSUE TITLE
[Docs update request] Unhelpful GCP link

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/docs#427]
This GCP link in this doc isn't helpful for settings up a complete GCP cloud integration with Kubecost -- https://guide.kubecost.com/hc/en-us/articles/4412369153687-Cloud-Integrations

Can we update it so point to our own guide? I suspect there are other links that aren't optimal on this page, but I haven't tested.

cc @bstuder99

**Comment by dwbrown2** [comment]
I would propose that we link here: https://guide.kubecost.com/hc/en-us/articles/4407601816087

**Comment by bstuder99** [comment]
Done, https://github.com/kubecost/docs/commit/d65920e9b082a9aa3d33f6e96d5d4a2ab713c112

**Comment by bstuder99** [comment]
How do you mean? I just replaced the Google link with the article you mentioned.

**Comment by dwbrown2** [comment]
This link does not show you how to integrate Azure billing data with Kubecost: https://docs.microsoft.com/en-us/azure/cost-management-billing/costs/tutorial-export-acm-data?tabs=azure-portal

**Comment by bstuder99** [comment]
So just to be clear, on top of the GCP link we've replaced with a link to our own GCP OOC doc, we should also replace the current Azure link with our Azure OOC doc (this one: https://guide.kubecost.com/hc/en-us/articles/4407595936023-Adding-Azure-Out-of-Cluster-Cluster-Costs-into-Kubecost)

**Comment by bstuder99** [comment]
Azure and GCP links now go to our own docs
