### ISSUE TITLE
Document Bug Bounty Program

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/docs#429]
Proposal: add 
`We pay $250 for unique accepted security bug reports submitted to vulnerability-report@kubecost.com`

to our documentation.

**Comment by bstuder99** [comment]
Interesting idea. We have a few docs this content could go to. Has the protocol ever been implemented? I'm curious how often this has happened. We should also add a few more lines for the user explaining what to expect from their side; is there a form/template they should fill out describing the bug? How long would we take to test and respond to them, etc.

We have our main security doc that is more about SOC2: https://guide.kubecost.com/hc/en-us/articles/4407595978903-Security
We also have a broader getting started guide that includes a section of user contribution: https://guide.kubecost.com/hc/en-us/articles/4407595978903-Security
I think the best page would be our bug report guide: https://guide.kubecost.com/hc/en-us/articles/4407601805975-Capture-a-bug-report

**Comment by AjayTripathy** [comment]
It's different from our bug report since it's a security thing. https://www.facebook.com/whitehat is an example page.

**Comment by bstuder99** [comment]
Ok, so are you recommending we create a new doc for this content?

**Comment by bstuder99** [comment]
Anyways, I'm curious how fleshed out our policy is compared to the FB example linked. How would payment be distributed? Do we have stipulations on who is allowed to submit a bug report? Protocol, etc.

**Comment by dwbrown2** [comment]
@bstuder99 does the alias in #468 exist? I just tested and can find no response.

**Comment by dwbrown2** [comment]
@AjayTripathy is there any other guidance you can give for those reporting?
