### ISSUE TITLE
Creation of a Federated ETL doc

### ISSUE THREAD

**Issue by bstuder99** [kubecost/docs#432]
I have been discussing with Kaelan and Adam the creation of a Federated ETL doc using content from a Google Doc linked in the release notes. I'm finding the technical terminology described a bit dense and confusing, so I'm hoping I can get some feedback on my comments to clear things up before the doc is published. I will link the PR here when I have the official draft.

Doc: https://docs.google.com/document/d/1Y0ttRo_YRs80UH-exnufHl32168cTETJA5Ld3ZCOwlc/edit#heading=h.m6e340wq0pvj

**Comment by kaelanspatel** [comment]
@bstuder99 Thanks for taking a look Brett. I've edited the docs and responded to your feedback. I know some of the terminology (Federated vs Federator) is confusing, hopefully its a little more clear now.

**Comment by bstuder99** [comment]
Great, thanks for the feedback. Let me start drafting up a doc

**Comment by bstuder99** [comment]
Doc is live https://guide.kubecost.com/hc/en-us/articles/10015110616599-Federated-ETL
