### ISSUE TITLE
Something doesn't appear to be working in Kubecost docs search ranking

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/docs#480]
Doing a Google search for [Kubecost High Availability](https://www.google.com/search?q=kubecost+high+availability) doesn't yield this [docs page](https://docs.kubecost.com/install-and-configure/advanced-configuration/high-availability):

<img width="1456" alt="image" src="https://user-images.githubusercontent.com/298359/207411799-2d5bfdc6-4eb6-4611-9ad4-f246c1a29b6c.png">

In fact, another resource is ranked above all other Kubecost results:

<img width="993" alt="image" src="https://user-images.githubusercontent.com/298359/207411611-79c7216c-464e-4661-bd3e-c6fca439141c.png">

This makes me think that something is wrong with Kubecost documentation SEO. 

cc @robfaraj @teevans for input

**Comment by Adam-Stack-PM** [comment]
@dwbrown2, It looks like our site map is pointing towards gitbooks.kubecost.com not docs.kubecost.com.  Example https://gitbook.kubecost.com/install-and-configure/advanced-configuration/high-availability and does not look like google is crawling our **docs site.** 

Fixing this and getting it submitted to google would be the first step.  We should prioritize fixing this. Fixing SEO items is a pin in the butt and takes time.


Current Sitemap: https://docs.kubecost.com/sitemap.xml

**Comment by teevans** [comment]
I'm one of the dumber people when it comes to SEO. - However, @robfaraj - I'm betting my prized cow on the fact this is because we're using the reverse proxy method.

**Comment by robfaraj** [comment]
was out today. just catching up. looks like we will have to intercept requests to /sitemap.xml and serve our own. we can discuss in tomorrow's meeting

**Comment by teevans** [comment]
@robfaraj - I figured that was it. Fixed nginx to replace the bad url with the new. 

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/3982846/207514652-70119b67-9f3e-43c8-84e8-857e5f0a745a.png">

**Comment by dwbrown2** [comment]
@teevans @Adam-Stack-PM @robfaraj amazing, huge thanks for the quick investigation + fix! 

@robfaraj I imagine this had a pretty big impact on Kubecost search engine rankings over the recent weeks... any way to measure the impact & monitor going forward?

**Comment by davestrandburg** [comment]
@dwbrown2 - I setup Google Search Console this morning for docs.kc - it's populating right now.  I don't think they provide search stats prior to initialization, but we'll have a better eye on things moving forward.

cc @robfaraj

**Comment by robfaraj** [comment]
closing this out as @davestrandburg resolved the user-agent issue preventing google-bot from accessing the correct sitemap from the reverse proxy
