### ISSUE TITLE
Assets API documentation doesn't provide detail

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/docs#499]
In my view the API documentation link provided here isn't very helpful, it doesn't provide detail on API parameters or responses. I believe it was originally designed for the Assets UI. https://github.com/kubecost/docs/blob/main/apis.md

Something like this feels far more useful: https://github.com/kubecost/docs/blob/main/allocation.md

**Comment by bstuder99** [comment]
Hmm, I see what you mean. So that goes to the Assets web UI page for some reason, and instead it should go to our Assets API page. Let me fix that. https://docs.kubecost.com/apis/apis/assets-api

**Comment by bstuder99** [comment]
API content is going to be reworked this month entirely to be more consistent with params and responses, using GitBook's integrated API tools.
