### ISSUE TITLE
Update the icon in the tab navigation to be the kubecost logo without a whitebackground

### ISSUE THREAD

**Issue by kwombach12** [kubecost/docs#520]
When you have the docs open as a tab, it has the small kubecost logo with a white background which is inconsistent with the rest of the kubecost resources (product, website, etc.)
<img width="705" alt="Screenshot 2023-01-23 at 4 55 34 PM" src="https://user-images.githubusercontent.com/86785820/214158783-6ba77ba4-9941-4abe-a674-205ec46de503.png">

**Comment by bstuder99** [comment]
Ok, ran a .png into GitBook and it should be updated.

**Comment by kwombach12** [comment]
Thanks @bstuder99 looks great!
