### ISSUE TITLE
Anchors on alerts page not working

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/docs#526]
The last two anchors don't seem to be routing to the right page content. Any chance this is happening on other pages?

<img width="886" alt="image" src="https://user-images.githubusercontent.com/298359/214689722-2a838a26-bdf2-434a-a3e9-77ae4ba06817.png">

https://github.com/kubecost/docs/blob/main/alerts.md#type-cluster-health
https://github.com/kubecost/docs/blob/main/alerts.md#type-kubecost-health-diagnostic

**Comment by bstuder99** [comment]
Yep I just noticed this. That numbered list was reformatted and a few of the headers they link to were changed. All of this was fixed in a series of PRs that fixed broken links across the repo
