### ISSUE TITLE
Add documentation for how to to edit ETL store duration

### ISSUE THREAD

**Issue by kwombach12** [kubecost/docs#540]
Users want to know how to edit their ETL store so that they can, for example, extend their ETL storage to 365 days (from the default of 90). 

from @nikovacevic, this can be done in values.yaml:
`kubecostModel: 
etlDailyStoreDurationDays: 120`

**Comment by dwbrown2** [comment]
Don't know technical limitations but would you ever want to expose this config in the Kubecost UI?

**Comment by jessegoodier** [comment]
> Don't know technical limitations but would you ever want to expose this config in the Kubecost UI?

Would there be risk of a user setting that to something undesirable? 
Perhaps give visibility in UI but force setting in helm?

**Comment by nikovacevic** [comment]
The pessimist in me says... there's always a risk of a user setting something undesirable. Haha. I love the idea of UI for visibility, but helm for editing -- in all things.

**Comment by AjayTripathy** [comment]
+1 for UI visibility but forcing setting in helm

**Comment by kwombach12** [comment]
I like that experience as well (configure in helm with visibility in the UI).

**Comment by bstuder99** [comment]
https://github.com/kubecost/docs/issues/540 Starting point, but I think we still need to add details for this upcoming release to clarify how to not break Kubecost by setting store duration super high, and describing interaction w/ Prom/Thanos

**Comment by bstuder99** [comment]
Wrong link, PR is here https://github.com/kubecost/docs/pull/583
