### ISSUE TITLE
Overview page suggestions

### ISSUE THREAD

**Issue by jessegoodier** [kubecost/docs#545]
A couple of suggestions on the overview page:

```
Advanced Configuration
[Allocating out of cluster costs (AWS)](https://guide.kubecost.com/hc/en-us/articles/4407596810519)
[Allocating out of cluster costs (Azure)](https://guide.kubecost.com/hc/en-us/articles/4407595936023)
[Allocating out of cluster costs (GCP)](https://guide.kubecost.com/hc/en-us/articles/4407601816087)
[AWS Spot feed integration](https://github.com/install-and-configure/install/cloud-integration/aws-cloud-integrations/aws-spot-instances#spot-data-feed-integration)
```

Could be: 
```
Cloud Billing Integration:
[AWS](https://guide.kubecost.com/hc/en-us/articles/4407596810519)
[Azure](https://guide.kubecost.com/hc/en-us/articles/4407595936023)
[GCP](https://guide.kubecost.com/hc/en-us/articles/4407601816087)
```

Potentially remove this, IMO it is not worthy of a link from the overview page considering the limited value.

``` 
[AWS Spot feed integration](https://github.com/install-and-configure/install/cloud-integration/aws-cloud-integrations/aws-spot-instances#spot-data-feed-integration)
```

Regardless of the wording, the AWS out of cluster link should point to the cloud-integration page like the other providers.
which is: https://docs.kubecost.com/install-and-configure/install/cloud-integration/aws-cloud-integrations

![image](https://user-images.githubusercontent.com/31039225/217372136-85279205-183f-406f-ad45-ea0351734d92.png)

**Comment by bstuder99** [comment]
This is starting to confuse me the more I look at it (the page itself, not your PR). Why are all our links labeled for Out of cluster guides but instead go to Billing Integrations? To answer your noticing the AWS page is different, this link broke a while back and I assumed the OOC page is where it was intended to go.

I like these suggestions, I'll fix it today.

**Comment by srpomeroy** [comment]
OOC nomenclature is held over from when we used to include external costs in the cost allocation view. Billing integration was how you made that work. All for updating the naming and the page.
