### ISSUE TITLE
Document AWS Reconciliation Methodology

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/docs#55]
Document how we join the CUR with providerIds for savings plans, spot nodes, and reserved instances.

**Comment by teevans** [comment]
@AjayTripathy - Is this relevant to [this](https://guide.kubecost.com/hc/en-us/articles/4407596809111-AWS-Node-Price-Reconciliation-Methodology)?

**Comment by AjayTripathy** [comment]
Yes, I think this can be closed for now.
