### ISSUE TITLE
Use node exporter service from another namespace

### ISSUE THREAD

**Issue by MikeAleksa** [kubecost/docs#563]
Is it possible to use an existing node exporter deployment in a different namespace?

I have a node exporter daemonset running from a prometheus-stack helm deployment and would prefer to use this node exporter daemonset than run two daemonsets, but I don't see anywhere to set for example a static URL to the node exporter service. Is that possible?

**Comment by thomasvn** [comment]
@MikeAleksa Yes, you should be able to use your own node-exporter! There will be a fix going into v1.101 which will automatically scrape all node-exporter service endpoints: https://github.com/kubecost/cost-analyzer-helm-chart/pull/1982
