### ISSUE TITLE
Document labelMappingConfigs

### ISSUE THREAD

**Issue by ivankube** [kubecost/docs#580]
re: https://github.com/opencost/opencost/issues/1734

To use a custom tags mapping, should the mapping be:

        helm:
          parameters:
            - name: kubecostProductConfigs.labelMappingConfigs.enabled
              value: 'true'
            - name: kubecostProductConfigs.labelMappingConfigs.namespace_external_label
              value: 'mycompanybilling:namespace'
            - name: kubecostProductConfigs.labelMappingConfigs.cluster_external_label
              value: 'mycompanybilling:cluster'

or should it be:

        helm:
          parameters:
            - name: kubecostProductConfigs.labelMappingConfigs.enabled
              value: 'true'
            - name: kubecostProductConfigs.labelMappingConfigs.namespace_external_label
              value: 'mycompanybilling_namespace'
            - name: kubecostProductConfigs.labelMappingConfigs.cluster_external_label
              value: 'mycompanybilling_cluster'

**Comment by bstuder99** [comment]
Just went through the original issue on this, can we get clarification as to which mapping example here should be used? This is ripped right from the Opencost issue and I don't think anyone in the thread clarified.

**Comment by ivankube** [comment]
I believe the second mapping example is correct. We also provide some examples in https://github.com/kubecost/cost-analyzer-helm-chart/blob/ef50e9b959e5b91890333b047830d604ec37d112/cost-analyzer/values.yaml#L947-L966:

For example
```
#    namespace_external_label: "kubernetes_namespace" # external labels/tags are used to map external cloud costs to kubernetes concepts
#    cluster_external_label: "kubernetes_cluster"

**Comment by bstuder99** [comment]
Resolved via https://github.com/kubecost/docs/pull/610
