### ISSUE TITLE
Not clear how to enabled accurate network costs

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/docs#609]
Can we make it really clear in this document? https://docs.kubecost.com/using-kubecost/getting-started/cost-allocation/network-allocation

A clear link saying "Setup" or something similar would help IMO.

**Comment by bstuder99** [comment]
I thought I'd added this content, then I remembered it exists here: https://docs.kubecost.com/install-and-configure/advanced-configuration/network-costs-configuration#enabling-network-costs
Where are you being linked to the above doc on Network Allocation? It might be better to link to this section (which can be accessed via a hyperlink in the Network Allocation doc on the daemonset

**Comment by bstuder99** [comment]
Ok, I've updated the descriptions and included a banner which links directly to enabling the daemonset: https://docs.kubecost.com/using-kubecost/getting-started/cost-allocation/network-allocation

**Comment by bstuder99** [comment]
We should probably clarify that this can be done after Helm install, will issue a change on that as well
