### ISSUE TITLE
kubecost api particular pod metrics

### ISSUE THREAD

**Issue by rudhrarai** [kubecost/docs#628]
Hi,

I am trying to fetch particular pod cost data using kubecost allocation api.
I am using below request.
```
curl https://qa-opencost.nexla.com/model/allocation/compute \
  -d window=24h \
  -d resolution=1m \
  -d aggregate=pod \
  -d accumulate=false \
  -G
```

Right now it is giving me all the pods data in each request, which is creating heavy load on kubecost and prometheus.
Is it possible if i can get the cost data of particular pod only?

**Comment by thomasvn** [comment]
@rudhrarai For Kubecost, if you are using the `/model/allocation` endpoint, I believe you can use the `filterPods` parameter. https://docs.kubecost.com/apis/apis-overview/allocation

However, if you are using the `/model/allocation/compute` endpoint, these filters may still be a work in progress as described in: https://github.com/opencost/opencost/issues/1772
