### ISSUE TITLE
Update OpenCost Product Comparison

### ISSUE THREAD

**Issue by thomasvn** [kubecost/docs#629]
The doc ["OpenCost Product Comparison"](https://docs.kubecost.com/architecture/opencost-product-comparison) states that Kubecost is differentiated from OpenCost in that it has a Helm install option, and a UI. However, OpenCost now provides both those features:

* https://github.com/opencost/opencost-helm-chart
* https://github.com/opencost/opencost/tree/develop/ui

**Comment by bstuder99** [comment]
Ok, I've taken a swing at this to be more accurate. I don't like the way GitBook cuts off most tables and inline code blocks, so I may be looking for a way of reorganizing this info. Maybe a Kubecost Free vs. OpenCost comparison would be more meaningful to users.
