### ISSUE TITLE
Feature Request: Add an OpenCost integrations page

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/docs#630]
Picturing this page highlighting things like the following:

* Currently supported integrations: Prometheus/Cortex/Thanos, Grafana, Kubecost, Vantage, and others
* Recommended steps for an integration: i.e. deploy + ingest metrics

**Comment by bstuder99** [comment]
Acknowledging this, have reached out to Matt Ray and will have this up soon

**Comment by bstuder99** [comment]
PR created, see above
