### ISSUE TITLE
Dropdown for Allocations API is creating newlines throughout the sentence

### ISSUE THREAD

**Issue by thomasvn** [kubecost/docs#665]
Screenshot attached

<img width="711" alt="Screenshot 2023-06-08 at 12 39 23 PM" src="https://github.com/kubecost/docs/assets/11251627/ef547a3d-5239-4a29-b740-a754666b242f">

**Comment by bstuder99** [comment]
I have contacted GitBook about this before and have observed it across our API docs. They think we are doing it manually because it appears in the raw doc itself. Obviously not the cause of the problem. I have corrected this multiple times, will ask them again to look.

**Comment by thomasvn** [comment]
@bstuder99 Great thanks for the update!

**Comment by bstuder99** [comment]
Docs have been manually updates but I will look out for this occurring in the future.
