### ISSUE TITLE
Document specific upgrade path for EKS add-on

### ISSUE THREAD

**Issue by rossfisherkc** [kubecost/docs#689]
Our doc
https://docs.kubecost.com/install-and-configure/install/provider-installations/aws-marketplace-install

Doesn't mention upgrade path and following
https://docs.kubecost.com/install-and-configure/install#updating-kubecost

is not valid for that offering

Discussion starting here for notes:
https://kubecost.slack.com/archives/C02E0C0003W/p1689784069430469

At the least, be sure to add a note to https://docs.kubecost.com/install-and-configure/install#updating-kubecost about https://docs.kubecost.com/install-and-configure/install/provider-installations/aws-marketplace-install to point the user to the right place. We may also want to spin off the "updating-kubecost" section into into it's own doc if necessary

**Comment by bstuder99** [comment]
Or is "EKS Add-on" meant as an add-on to the base AWS Marketplace install?

**Comment by bstuder99** [comment]
@rossfisherkc Can you let me know the status of this? I believe this was shelved, just want confirmation before I close this.
