### ISSUE TITLE
Contributing guide needed

### ISSUE THREAD

**Issue by chipzoller** [kubecost/docs#700]
## Problem

This documentation is a public repo and serves an open source (core) project as well as a commercial product. There is currently no contribution guide, style guide, etc informing potential contributors on how to go about making docs suggestions and changes. This is a common feature for most similar projects.

## Solution

Develop a contributing guide for documentation. While there are many models than can be chosen, the Kyverno project's website contribution guide can be found [here](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).

**Comment by bstuder99** [comment]
Current contribution guide for OpenCost which has not been updated in a while: https://github.com/opencost/opencost/blob/develop/CONTRIBUTING.md
We used to have a similar guide for Kubecost, but it really was just reduced to "submit a PR if you have a suggestion" which most open source users are familiar with. I see how this can go hand-in-hand with PR templates, but really contributions are not super common. We get maybe 1-3 user contributions per month.

**Comment by chipzoller** [comment]
Part of the contribution is just instructing users on how they can build the site locally to test changes. I actually struggled with this myself since the site uses GitBook and has loads of dependencies. Even if that were the main focus of such a guide, it'd be valuable.

**Comment by bstuder99** [comment]
Contributions through GitBook should only be performed internally. For external users, GH contributions should work the same as any other repo.

**Comment by chipzoller** [comment]
But the site is exclusively hosted on GitBook, and there needs to be a way for users to locally build and preview the site. This flow is typically used when contributions are made via the git flow and not graphically at GitBook directly.

**Comment by bstuder99** [comment]
It's not actually, GitHub is the original source of most of our docs content with GB being a FE tool that syncs with our docs repo. Docs changes can be made through either platform, but GH is our public pathway for users while GB is used only internally. Users cannot submit changes through GB. Previewing is done as usual through GH's Preview feature.

**Comment by chipzoller** [comment]
Sounds like this may not be that valuable after all.
