### ISSUE TITLE
Implement a link checker Action

### ISSUE THREAD

**Issue by chipzoller** [kubecost/docs#703]
## Problem

Broken links always occur in documentation, and finding and fixing them provides a better reader experience.

## Solution

Implement an automated link checker as a GitHub Action which can scour the documentation periodically and report on any broken links. For example, one implementation in the Kyverno project is [here](https://github.com/kyverno/website/blob/main/.github/workflows/check-links.yaml), and this can basically be copied-and-pasted to this repo.

**Comment by bstuder99** [comment]
Will this only check for 404s, or any link that doesn't seem correct? We use lots of example Kubecost links, offsite links requiring logins, and a few other detected hyperlinks which run back as errors when I've used broken link check tooling. PR is already up: https://github.com/kubecost/docs/pull/704, just want to know more about how this works before we merge.

**Comment by chipzoller** [comment]
The action used in #704 does more than just 404s. Any non-successful exit code will be surfaced in the reports. There will be some noise there as well, and there is a config file format that's supported to filter those out.

**Comment by bstuder99** [comment]
Ok. It looks like this cron expression is testing daily, correct? Where are its findings published or sent? Will they auto-create an issue?

**Comment by chipzoller** [comment]
It runs daily, yes. The findings will be shown by inspecting the Action run directly. The component which auto-creates an issue has been commented out (disabled) because of the noise it has the tendency to create. The typical flow is once the initial issues are addressed and subsequent scans come back clean, the issue-opening action is enabled from that point forward.

**Comment by chipzoller** [comment]
Closed in #704.

**Comment by chipzoller** [comment]
Here's your first answer:

https://github.com/kubecost/docs/actions/runs/5927926191
