### ISSUE TITLE
Incorporate link checking in CI

### ISSUE THREAD

**Issue by chipzoller** [kubecost/docs#705]
Once the [check links workflow](https://github.com/kubecost/docs/blob/main/.github/workflows/checks-links.yaml) has been settled and with a config file covering false positives and corner cases, incorporate this into CI checks so it helps maintainers determine the risk of the PR.

**Comment by chipzoller** [comment]
Partially addressed in #704

**Comment by srpomeroy** [comment]
Addressed in #725
