### ISSUE TITLE
Add documentation for our Cluster Sizing API

### ISSUE THREAD

**Issue by kwombach12** [kubecost/docs#714]
Users who want to use Kubecost's Cluster Sizing API have no documentation on how to use.

**Comment by bstuder99** [comment]
Ok, can you provide more information on this? Do you have a link to a design doc, or an SME I should talk to? DM me on any private details

**Comment by kwombach12** [comment]
@bstuder99 Unfortunately, I'm a bit blind on this as well without any docs :). @cliffcolvin can someone on the BE team provide some guidance here?

**Comment by bstuder99** [comment]
Closing https://docs.kubecost.com/apis/apis-overview/cluster-right-sizing-recommendation-api
