### ISSUE TITLE
[Bug] Network Costs link goes to google

### ISSUE THREAD

**Issue by dramich** [kubecost/docs#718]
### Page link

https://docs.kubecost.com/architecture/architecture

### Description

This link goes to google https://github.com/kubecost/docs/blob/main/architecture.md?plain=1#L14 instead of a docs page

### Expected behavior

Go to a kubecost docs page

**Comment by bstuder99** [comment]
Thank you bringing this to our attention. The link is corrected here: https://github.com/kubecost/docs/pull/719
