### ISSUE TITLE
kube_pod_container_resource_requests_memory_bytes is DEPRECATED but meanwhile Kubecost required

### ISSUE THREAD

**Issue by chris-ng-scmp** [kubecost/docs#74]
I am running cost-model:prod-1.76.0 on a K8S cluster in 1.18

`kube_pod_container_resource_requests_memory_bytes` mertic is DEPRECATED in the latest `kube-state-metrics` version [2.0](https://github.com/kubernetes/kube-state-metrics/blob/release-2.0/docs/pod-metrics.md) , but KubeCost required it

![image](https://user-images.githubusercontent.com/2509212/112783463-f4f7e600-9081-11eb-99f6-6fc4e0ecba59.png)

ref: https://github.com/kubernetes/kube-state-metrics/issues/1269

**Comment by dwbrown2** [comment]
kube-state-metrics 2.0 production release was three days. We have begun investigating and will share updates when they are available!

**Comment by mrliptontea** [comment]
I ran into this too now.

While a stable release of kube-state-metrics v2 was made public only a few days ago, v2.0.0-rc.1 has been the only fully supported version for Kubernetes 1.17 and higher, see https://github.com/kubernetes/kube-state-metrics/tree/v2.0.0-rc.1#compatibility-matrix

Older versions only go as high as 1.16: https://github.com/kubernetes/kube-state-metrics/tree/v1.9.8#compatibility-matrix

**Comment by dwbrown2** [comment]
ksm v2 was released long after kubernetes 1.17. many users still successfully run ksm 1.x on these builds. 

we have an internal design we are discussing for these newer builds!

**Comment by DerrickMartinez** [comment]
ksm v2 release is coming up on 2 months soon. Any update?

**Comment by mrliptontea** [comment]
> ksm v2 was released long after kubernetes 1.17. many users still successfully run ksm 1.x on these builds.
> 
> we have an internal design we are discussing for these newer builds!

`kube_pod_container_resource_requests` metric has been present in ksm since 1.9 so it's available to all currently supported versions of ksm and Kubernetes.

**Comment by mrliptontea** [comment]
Correction they've been added in [v1.4.0-rc.0](https://github.com/kubernetes/kube-state-metrics/blob/v2.0.0/CHANGELOG.md#v140-rc0--2018-08-06).

There is really no reason to keep `kube_pod_container_resource_requests_cpu_cores` and `kube_pod_container_resource_requests_memory_bytes`.

**Comment by dwbrown2** [comment]
There is a reason to keep these metrics. It's because we support users running older builds and many users have dropped these metrics historically. 

We're working on this for both cadvisor and ksm now.

**Comment by pierluigilenoci** [comment]
All versions of Kubernetes below 1.19 have come to EOL:

* 1.16: 2 September 2020 
* 1.17: 30 January 2021 
* 1.18: 30 April 2021 

Version 1.19 still has a little over 4 months of life and 1.20 just 7 months. The clock runs fast.

I understand the will to maintain backward compatibility but it shouldn't happen to the detriment of those who update their clusters. 😉

**Comment by mhulscher** [comment]
Great to see that this is being worked on. We're suffering from the same issue. For reference:
* we've been running EKS 1.19 for a month now and we're looking to upgrade to 1.20 in the near future
* we're running kube-state-metrics:v2.0.0 as installed by https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack

**Comment by mhulscher** [comment]
Follow-up question: does kubecost expose a single API that we can query to tell us if it is missing metrics? Something like a health-check? We could adopt this in our own e2e tests before upgrading any other components (kube-prometheus-stack, k8s, etc).

**Comment by pierluigilenoci** [comment]
@mhulscher I discovered them digging inside the Kubecost UI, checking the API call ;) 

<img width="924" alt="Screenshot 2021-05-26 at 17 42 24" src="https://user-images.githubusercontent.com/36044817/119690274-d0ce4080-be49-11eb-8f4d-ce32d5358227.png">

Check the `/diagnostics.html` page of the UI.

**Comment by mhulscher** [comment]
@pierluigilenoci I found these as well, but these are unreliable and likely to change in the future. These queries still rely on the (as of now) deprecated metrics from cAdvisor en kube-state-metrics. I would prefer an API-call that performs all required queries and tells me whether they have succeeded or not.

**Comment by pierluigilenoci** [comment]
If you want that I think the only solution is to open a feature request. 😜

**Comment by dwbrown2** [comment]
Yeah, might be worth discussing in a separate thread. We recommend our [diagnostic alert](https://github.com/kubecost/docs/blob/master/alerts.md#type-kubecost-health-diagnostic) as a general purpose solution.

**Comment by pierluigilenoci** [comment]
Can this issue be closed?

**Comment by AjayTripathy** [comment]
Yes, I believe so.
