### ISSUE TITLE
[Enhancement] No documentation currently exists for Kubecost's Admission Controller feature

### ISSUE THREAD

**Issue by thomasvn** [kubecost/docs#749]
### Description

Specifically, the feature that this Helm config enables:

```yaml
kubecostAdmissionController:
  enabled: true
```

Note, that this was released as an experimental/beta feature. Its rough idea was to allow Kubecost admins to set budgets for certain deployments/namespaces. If you were to exceed the budget, the admission controller would not let you create the newly requested resource.

To get more info about the feature, we may need to talk to the engineers that wrote it. @bstuder99 Also your call as to whether it is a priority to further document this feature.

**Comment by bstuder99** [comment]
I was explaining this in [the Admission Controller blog PR](https://github.com/kubecost/blog/pull/140), but I believe I asked @michaelmdresser about whether we should be documenting `kubectl predict`, and he said this content should remain in its Git repository. I forget the specific argument used, but I think it has to do with this not exactly being a part of Kubecost, but rather an extra experimental feature we designed. If he feels differently, I can take some steps to start putting a guide together for `kubectl predict` and the Admission Controller.

**Comment by bstuder99** [comment]
The Git repo is here, https://github.com/kubecost/kubectl-cost

**Comment by bstuder99** [comment]
It doesn't look like the Admission Controller itself is documented in this repo, so maybe we could work on adding that.
