### ISSUE TITLE
[Enhancement] Refine Ingress Warning

### ISSUE THREAD

**Issue by kwombach12** [kubecost/docs#766]
### Description

Strenghthen our ingress warning so its more clear to users that their endpoint is open to the world and that we recommend securing it.

**Comment by bstuder99** [comment]
Can you be more descriptive with this? This isn't a request for copy changes to the UI itself, right? We can provide guidance, but a doc can't warn someone about a condition as it can't determine the status of their endpoint.

**Comment by kwombach12** [comment]
@bstuder99 just opened a PR for this - the goal is to make this warning a bit more clear and urgent for teams who less familiar with networking best practices.
