### ISSUE TITLE
[Enhancement] Update Budget API docs

### ISSUE THREAD

**Issue by thomasvn** [kubecost/docs#770]
### Description

Need to update [Budget API Docs](https://docs.kubecost.com/apis/apis-overview/budget-api) because v1.107 will be officially deprecating the following APIs:

- `/model/budget/recurring/set`
- `/model/budget/recurring/list`
- `/model/budget/recurring/delete`

in favor of the `/model/budget` endpoint. New API implemented in PR https://github.com/kubecost/kubecost-cost-model/pull/1378. Old API removed from codebase in PR https://github.com/kubecost/kubecost-cost-model/pull/1805.

Need to defer to @avrodrigues5 for further details as to how the new endpoint works.

**Comment by thomasvn** [comment]
It may be worthwhile to move this doc to the "Deprecated APIs" directory, then create a fresh new doc for the new Budgets endpoint

**Comment by bstuder99** [comment]
#783 contains 1.107 updates for this API, thanks for bringing this to my attention
