### ISSUE TITLE
[Bug] list of APIs supporting v2 filters appears stale

### ISSUE THREAD

**Issue by mattray** [kubecost/docs#786]
### Page link

https://docs.kubecost.com/apis/apis-overview/filters-api#using-filters

### Description

I noticed that https://docs.kubecost.com/apis/apis-overview/cloud-cost-api supports filtering but it's not listed in the [filters-api page](https://docs.kubecost.com/apis/apis-overview/filters-api#using-filters) as using them. I figure the page is probably out-of-date.

### Expected behavior

APIs with filters are linked.

**Comment by bstuder99** [comment]
So you may be right on this, but I wanted to clarify a few details:
The filtering options available to the Cloud Cost API are specific for individual categories (ie `filterServices` or `filterLabels`, whereas the Filtering Language doc describes an advanced method of combining or excluding certain names or groups. Certain aspects of the filtering language conform only to 1 or 2 of the listed APIs. I would see if @michaelmdresser can confirm this for me, but this was my understanding. If the Cloud Cost API also supports advanced filtering, I'll add it to the list.

**Comment by michaelmdresser** [comment]
I believe Cloud Cost does not yet support the advanced "v2.1" filter language. @Sean-Holcomb can you confirm?

**Comment by Sean-Holcomb** [comment]
opencost and aggregator CloudCost endpoints do but normal OnPrem CloudCosts do not
