### ISSUE TITLE
[Enhancement] SetUp autorecomendations Worng link inside Dashboard

### ISSUE THREAD

**Issue by mathgonzlez** [kubecost/docs#811]
### Description

Hi, I found that the "Set up auto recommendations" option inside UI points to a link that no longer exists in the repository:
https://github.com/kubecost/docs/blob/main/auto-request-sizing.md
Thank you!

**Comment by bstuder99** [comment]
Thank you for pointing this out. The correct location for the file is docs/using-kubecost/navigating-the-kubecost-ui/savings/auto-request-sizing/auto-request-sizing.md. Can you elaborate where you are finding this broken link?
