### ISSUE TITLE
[Bug] Broken links

### ISSUE THREAD

**Issue by chipzoller** [kubecost/docs#827]
### Page link

https://github.com/kubecost/docs/actions/runs/6998963656

### Description

Broken links. See run https://github.com/kubecost/docs/actions/runs/6998963656

### Expected behavior

No broken links.

**Comment by chipzoller** [comment]
@bstuder99, are you getting emails when the link checker fails? If not, you should subscribe.

**Comment by bstuder99** [comment]
Those should be fixed in this PR: https://github.com/kubecost/docs/pull/825/files

**Comment by chipzoller** [comment]
Closed by #825
