### ISSUE TITLE
Remove mention of needing node-exporter to run core Kubecost

### ISSUE THREAD

**Issue by csfangy** [kubecost/docs#83]
Node-exporter is optional, not essential to core Kubecost. Please update https://github.com/kubecost/docs/blob/master/architecture.md#kubecost-core-architecture-overview. 

It gives you a little extra context on the overview page about what your kubelets are doing, but no core allocation models are affected.

**Comment by dwbrown2** [comment]
I've just created https://github.com/kubecost/docs/pull/84 would love to get your feedback!

**Comment by csfangy** [comment]
Everything LGTM. Line 19 should be also changed to:

`Today, the core Kubecost product can be run with just components 1, 3a, and 3b.`

**Comment by dwbrown2** [comment]
thank you! just updated.
