### ISSUE TITLE
[Bug] 404 on page Set Up Auto Recommendations

### ISSUE THREAD

**Issue by trungdlp-wolffun** [kubecost/docs#833]
### Page link

https://docs.kubecost.com/using-kubecost/navigating-the-kubecost-ui/savings/auto-request-sizing

### Description

<img width="579" alt="image" src="https://github.com/kubecost/docs/assets/93299415/a2d28144-604d-4ed0-9d93-4c9dbee0126c">

Click on `Set Up Auto Recommendations` -> 404

### Expected behavior

200

**Comment by bstuder99** [comment]
Thank you for bringing this to our attention. The correct link is https://docs.kubecost.com/using-kubecost/navigating-the-kubecost-ui/savings/container-request-right-sizing-recommendations, which should contain up-to-date information about the feature. Can you tell me what version of Kubecost you're running?

**Comment by trungdlp-wolffun** [comment]
@bstuder99 I run latest `kubecost` version.

```
Kubecost Info
API Version
1.107.1 (f87c784)

UI Version
1.107.1 (26227c95)

License Version
FREE
```

**Comment by bstuder99** [comment]
Ok, we should have a patch for this in the next Kubecost update.

**Comment by bstuder99** [comment]
As of v1.108 of Kubecost which released last month, this issue should be resolved. Please upgrade to the most recent version of Kubecost to receive a fix.
