### ISSUE TITLE
[Enhancement] Update references to OpenShift chart/values

### ISSUE THREAD

**Issue by chipzoller** [kubecost/docs#834]
### Description

The PR https://github.com/kubecost/cost-analyzer-helm-chart/pull/2815 brings support for OpenShift in the main Helm chart which obviates the need for the current and unmaintained fork at [kubecost/openshift-helm-chart](https://github.com/kubecost/openshift-helm-chart/tree/main).

Update the docs to point users to the new values file provided.

**Comment by bstuder99** [comment]
To confirm, you want any references to https://github.com/kubecost/openshift-helm-chart/blob/main/index.yaml to be replaced with our default values.yaml?

**Comment by chipzoller** [comment]
No, the docs need to be updated to remove references to kubecost/openshift-helm-chart. I can take care of a draft PR here.
