### ISSUE TITLE
[Enhancement] Image tag bumps from 108

### ISSUE THREAD

**Issue by chipzoller** [kubecost/docs#845]
### Description

Heads up that numerous image tags have been bumped as of 108 (see notes [here](https://github.com/kubecost/cost-analyzer-helm-chart/releases/tag/v1.108.0)) and so wherever these are documented will need to be updated.

**Comment by Ayush9026** [comment]
Hi @chipzoller sir i want to solve this issue.

**Comment by bstuder99** [comment]
Can you point to an example of an outdated image tag? Cross referencing our 1.108 release notes with our docs and don't see image versions usually ever being stated.
