### ISSUE TITLE
Azure OOC Documentation Step 3 still references AWS Tags

### ISSUE THREAD

**Issue by csfangy** [kubecost/docs#85]
Step 3: Tagging Azure resources

The table still refers to "AWS Tags."

**Comment by dwbrown2** [comment]
thanks @csfangy! 

@kbrwn would you be able to take this one? I believe this is reference -- https://github.com/kubecost/docs/blob/master/azure-out-of-cluster.md#step-3-tagging-azure-resources

**Comment by dwbrown2** [comment]
Kyle, know you're crazy busy so went ahead and knocked this out quickly with https://github.com/kubecost/docs/commit/4cfc60c5b2dbd8e8bf2bb89994213b86af00ba78. Let me know if you guys see any other references.
