### ISSUE TITLE
Question about Kubecost's logo

### ISSUE THREAD

**Issue by stefan-novak-brt** [kubecost/docs#932]
Hello,

I have a general inquiry/question about the design of the Kubecost's logo.

I previously worked on a NASA space mission called [MMS](https://en.wikipedia.org/wiki/Magnetospheric_Multiscale_Mission) which featured a [series of apogee raising maneuvers](https://en.wikipedia.org/wiki/File:MMSPhase2b_Pole_Jan2May2017.UHD3840_2160p30.webm) that was strategic for collecting data from Earth's magnetosphere.

When these maneuvers are visualized in a geocentric solar ecliptic frame, it looks oddly similar to Kubecost's logo:

![image](https://github.com/kubecost/docs/assets/101155994/4302b684-3997-445e-995d-9a490d88c460)

Is it possible to provide some credit of the logo design with the space mission design team for that NASA mission? :smile: 

Cheers!

**Comment by kwombach12** [comment]
@stefan-novak-brt WOW this is so fascinating! I don't think any of us here at Kubecost have heard of apogee raising maneuvers - I think the resemblance is just serendipitous. Thank you so much for sharing!!
