### ISSUE TITLE
[Bug] Not relevent error in 2.x

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/docs#951]
### Page link

https://docs.kubecost.com/troubleshooting/troubleshoot-install#the-kube-state-metrics-pod-fails-to-start-failed-to-list-v1beta1.ingress-and-or-failed-to-list-v1bet

### Description

Is this ksm issue relevent anymore given that it's no longer installed in 2.x?

cc @bstuder99 @jessegoodier 

### Expected behavior

Error reference removed in 2.1 docs?

**Comment by bstuder99** [comment]
Being addressed in #952
