### ISSUE TITLE
[Bug] Header image not loading

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/docs#965]
### Page link

https://docs.kubecost.com/using-kubecost/navigating-the-kubecost-ui/external-costs

### Description

<img width="1464" alt="image" src="https://github.com/kubecost/docs/assets/298359/0fb9fa9c-ddbf-47e9-96ce-5206a5aa3bd2">

### Expected behavior

All images to load. Are there other pages where images aren't loading?

**Comment by bstuder99** [comment]
I am seeing the image on my side. We've encountered this bug a week or two ago, it seems to be on GitBook's side. Images still load in their raw Markdown files on GitHub, so there's no problem with the image linking
