### ISSUE TITLE
[Bug] We need to tell people how to use Datadog costs

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/docs#967]
### Page link

https://docs.kubecost.com/using-kubecost/navigating-the-kubecost-ui/external-costs

### Description

In this page, we don't explain how people actually get value from the feature once it's configured. 

### Expected behavior

For example, where in the UI can they see these costs? What is the actual API endpoint and the parameters available?

**Comment by bstuder99** [comment]
Can you be more specific? The Datadog costs are displayed on the External Costs page, and can be additionally be tailored via the page's querying options

**Comment by dwbrown2** [comment]
Sorry wrote this quickly... I think there are two potential pieces of info that would be valuable:

1. How can I find this page? I don't think we highlight Monitor > External Costs anywhere
2. Are there APIs available? I don't think we reference here.

**Comment by bstuder99** [comment]
1. Never really thought about that, none of our monitoring pages mention this because they're described as Monitoring pages. Can make updates for this.
2. I'm going to meet with a core eng to go over this, no External Cost API doc exists at the moment.

**Comment by bstuder99** [comment]
Currently being addressed in #981 and #984
