### ISSUE TITLE
[Enhancement] Two ideas to improve external costs docs

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/docs#969]
### Description

Page: https://docs.kubecost.com/using-kubecost/navigating-the-kubecost-ui/external-costs

1. Can we highlight this implements the FOCUS spec and potentially reference a link?
2. Can we highlight this is built on OpenCost plugin? Can link to their docs / blog

**Comment by bstuder99** [comment]
I can link to [this](https://www.opencost.io/docs/integrations/datadog OpenCost dog on the Datadog plugin, but in their own words:
> These instructions are *very* rough and will continue to get revised as we approach release.
Not sure if this is where we want to send Kubecost users, but if they aren't consulting these steps for enabling External Costs we should be okay. Will reference the FOCUS spec also

**Comment by bstuder99** [comment]
Added FOCUS spec in #981
